version: "3"
services:
   lab:
      build:
         context: .
         dockerfile: Dockerfile
      container_name: ANN-Dream
      hostname: Jupyter
      ports:
         - 8888:8888
      volumes:
         - ./images:/root/notebooks/images

